### PR TITLE
Implement domain react forms package

### PR DESCRIPTION
**Pull request by alekseyzadorozhniy**

### CODE REVIEW

**Comment by vlasenko** [comment]
@zadorozhniyal @evgenijolshanskij I think we should plan for `i18n` support in validators from the very start, without such support their usefulness will be very limited

**Comment by vlasenko** [comment]
I mean we should have easy way for the developer to supply translations for validation messages

**Comment by evgenijolshanskij** [comment]
@vlasenko, yep, I think that's a good idea.

**Comment by vlasenko** [comment]
We should support not only predefined validators, but custom ones too

**Comment by vlasenko** [comment]
@evgenijolshanskij @alekseyzadorozhniy Thank you guys, looks good to me, feel free to merge!

**Pull request merged**
